name: Coverity Scan Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * SAT"

jobs:
  coverity:
    secrets: inherit
    uses: hrzlgnm/actions/.github/workflows/coverity-reusable.yml@deb1f469a2c763fe930b922c8b9cebadc5e92313 # v1.2.0
    with:
      coverity-email: ${{ secrets.COVERITY_NOTIFY_EMAIL }}
      coverity-token: ${{ secrets.COVERITY_SCAN_TOKEN }}
      extra-deps: "libgflags-dev libmnl-dev libspdlog-dev"
