name: Coverity Scan Reusable Workflow
on:
  workflow_call:
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest

    steps:
      - name: üîÑ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: üõ†Ô∏è Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            curl \
            libgflags-dev \
            libmnl-dev \
            libspdlog-dev \
            ninja-build

      - name: ‚öôÔ∏è Configure using CMake and Ninja
        run: |
          cmake -S . -B build -G Ninja

      - name: ‚ö°Scan with coverity
        uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
        with:
          email: ${{ secrets.COVERITY_NOTIFY_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          command: ninja
          working-directory: "${{ github.workspace }}/build"

      - name: üì§ Offer analysis tarball for inspection
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ github.event.repository.name }}_coverity_scan_upload_${{ github.sha }}
          path: build/cov-int.tgz
          if-no-files-found: error
