name: Reusable lint workflow

on:
  workflow_call:

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-gcc:v1@sha256:6fc43fc5ccd27230a3378050288524013fa848bfb879990ecccae97fa666b93f
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .

      - name: ğŸ“ Check clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +
