name: Reusable lint workflow

on:
  workflow_call:

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-gcc:v1@sha256:77d14d47a92453d47f43c6c5e9a8700e5a20bc4f6d8b7c4d97d81dd1364bc867
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ“ Check cmake format
        if: always()
        run: gersemi --check --diff .

  clang-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-gcc:v1@sha256:77d14d47a92453d47f43c6c5e9a8700e5a20bc4f6d8b7c4d97d81dd1364bc867
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        
      - name: ğŸ“ Check clang-format
        if: always()
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +
