name: Reusable lint workflow

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/monkas-github-builder:v1@sha256:94995fa470e435d56f9e17f24b146bc72913536b0798fca7229be1faf6cd8e4c
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ“ Check clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +
